site_name: iRacing Garage

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dangkv/iracing_garage
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dangkhoivo/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2024 <a href="https://github.com/dangkv"  target="_blank" rel="noopener">Dang Khoi Vo</a>
